---

- name: download helm
  get_url:
    url: https://storage.googleapis.com/kubernetes-helm/helm-v2.13.1-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz
    mode: '0644'

- name: untar helm.tar.gz
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp

- name: checking if the file /tmp/linux-amd64/helm exist
  stat:      
    path: /tmp/helm.tar.gz
  register: stat_result

- name: moving helm executable
  command: mv /tmp/linux-amd64/helm /usr/local/bin/helm
  when: stat_result.stat.exists == True

- name: moving tiller executable (with helm v3 this executable is gone)
  command: mv /tmp/linux-amd64/tiller /usr/local/bin/tiller
  when: stat_result.stat.exists == True
