---

- name: Copy K3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Register node-token file access mode
  stat:
    path: /var/lib/rancher/k3s/server
  register: p

- name: Change file access node-token
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"

- name: Read node-token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store Master node-token
  set_fact: 
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
    cacheable: yes

- name: Restore node-token file access 
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"

- name: Create directory .kube
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"

- name: Replace https://localhost:6443 by https://master-ip:6443
  replace:
    path: /home/{{ ansible_user }}/.kube/config
    regexp: 'https://localhost:6443'
    replace: 'https://{{master_ip}}:6443'

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: Kubectl Autocomplete to .bashrc of {{ ansible_user }}
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: 'source <(kubectl completion bash)'

- name: Kubectl Autocomplete to .bashrc of root
  lineinfile:
    path: /home/root/.bashrc
    line: 'source <(kubectl completion bash)'

- name: add KUBECONFIG to .bashrc of {{ ansible_user }}
    lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml'

- name: add KUBECONFIG to .bashrc of root
    lineinfile:
    path: /home/root/.bashrc
    line: 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml'

- name: add CATTLE_SERVER to .bashrc of {{ ansible_user }}
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: 'export CATTLE_SERVER=https://rancher

- name: add CATTLE_SERVER to .bashrc of root
  lineinfile:
    path: /home/root/.bashrc
    line: 'export CATTLE_SERVER=https://rancher

- include_tasks: install_helm.yml
- include_tasks: install_cert_manager.yml
