k3s_version: v1.0.0
ansible_user: vagrant
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
# 
# node_ip: "{{ hostvars[groups['node']]['ansible_host'] }}"
# This results with the following error:
## fatal: [node2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: ansible.vars.hostvars.HostVars object has no element [u'node2', u'node3']"}
# The node role will grab the node_ip now instead
