---

- name: download the node-token from k3s-master
  shell: scp root@k3s-master:/var/lib/rancher/k3s/server/node-token /vagrant/node-token

- name: rear the node-token from the copied file
  set_fact:
    token: "{{ lookup('file', '/vagrant/node-token') }}"

- name: grep the IP address of eth1
  shell: /sbin/ifconfig eth1 | grep 'inet ' | awk '{print $2}'
  register: node_ip

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
