---

- hosts: k3s-cluster
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
    - prep
    - prereq
    - download


- hosts: master
  #gather_facts: yes
  become: yes
  become_method: sudo
  roles:
    - k3s/master

- hosts: node
  #gather_facts: yes
  become: yes
  become_method: sudo
  roles:
    - k3s/node
